language: python

python: 3.6

sudo: true

before_install:
  - sudo apt-get update
  - sudo apt-get install linux-headers-$(uname -r)
  - wget 'http://us.download.nvidia.com/tesla/396.37/NVIDIA-Linux-x86_64-396.37.run'
  - sudo /bin/bash ./NVIDIA-Linux-x86_64-396.37.run -s
  - sudo nvidia-smi -pm 1
  - sudo nvidia-smi

install:
  - git clone https://github.com/pytorch/examples.git
  - cd examples/word_language_model
  - pip install -U pip
  - pip install -r requirements.txt --progress-bar off

script: python main.py --cuda --epochs 6 --tied && python generate.py --cuda
# script: python main.py --tied && python generate.py

